"""
Generate Synthetic Data Validation Form (500 reviews) for expert reviewers.
Includes all 500 synthetic reviews + generation methodology documentation.
"""

import json
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ── Styling ──────────────────────────────────────────────────────────────────
HEADER_FONT = Font(name="Calibri", bold=True, size=12, color="FFFFFF")
HEADER_FILL = PatternFill(start_color="2F5496", end_color="2F5496", fill_type="solid")
SECTION_FONT = Font(name="Calibri", bold=True, size=11, color="2F5496")
SECTION_FILL = PatternFill(start_color="D6E4F0", end_color="D6E4F0", fill_type="solid")
YELLOW_FILL = PatternFill(start_color="FFFFCC", end_color="FFFFCC", fill_type="solid")
LIGHT_GRAY = PatternFill(start_color="F2F2F2", end_color="F2F2F2", fill_type="solid")
WRAP = Alignment(wrap_text=True, vertical="top")
CENTER = Alignment(horizontal="center", vertical="center", wrap_text=True)
THIN_BORDER = Border(
    left=Side(style="thin"), right=Side(style="thin"),
    top=Side(style="thin"), bottom=Side(style="thin"),
)


def style_header_row(ws, row, max_col):
    for col in range(1, max_col + 1):
        cell = ws.cell(row=row, column=col)
        cell.font = HEADER_FONT
        cell.fill = HEADER_FILL
        cell.alignment = CENTER
        cell.border = THIN_BORDER


def style_data_cell(cell, yellow=False):
    cell.alignment = WRAP
    cell.border = THIN_BORDER
    if yellow:
        cell.fill = YELLOW_FILL


# ── Load data ────────────────────────────────────────────────────────────────
with open("/Users/fabihajalal/Desktop/Review Agent/ReviewAgent/data/raw/sample_reviews.json") as f:
    reviews = json.load(f)

wb = openpyxl.Workbook()

# ══════════════════════════════════════════════════════════════════════════════
# SHEET 1: Instructions
# ══════════════════════════════════════════════════════════════════════════════
ws1 = wb.active
ws1.title = "Instructions"
ws1.sheet_properties.tabColor = "2F5496"

instructions = [
    ("SYNTHETIC DATA VALIDATION FORM — ReviewAgent", HEADER_FONT, HEADER_FILL),
    ("", None, None),
    ("Purpose", SECTION_FONT, SECTION_FILL),
    ("This form asks you to validate 500 synthetic app store reviews generated by a template-based script.", None, None),
    ("These reviews are used to train a multi-label RoBERTa classifier for the ReviewAgent pipeline.", None, None),
    ("The MAALEJ dataset (5,008 real reviews) lacks two categories: performance complaints and compatibility issues.", None, None),
    ("Synthetic reviews fill these gaps. Your validation ensures they are realistic enough for training.", None, None),
    ("", None, None),
    ("What to Evaluate (Sheet 2 — All 500 Reviews)", SECTION_FONT, SECTION_FILL),
    ("For EACH of the 500 reviews, score the following in the YELLOW columns:", None, None),
    ("", None, None),
    ("  1. Realism (1–5):", None, None),
    ("     1 = Completely artificial (robotic, no human would write this)", None, None),
    ("     2 = Mostly artificial (template-like, recognizable pattern)", None, None),
    ("     3 = Acceptable (could pass as a real review with minor issues)", None, None),
    ("     4 = Realistic (natural language, believable content)", None, None),
    ("     5 = Indistinguishable from a real app store review", None, None),
    ("", None, None),
    ("  2. Category Correctness (Y / N):", None, None),
    ("     Is the assigned category (bug_report, feature_request, etc.) correct for this review text?", None, None),
    ("", None, None),
    ("  3. Comments (optional):", None, None),
    ("     Flag anything: wrong category, unrealistic phrasing, missing context, suggestions.", None, None),
    ("", None, None),
    ("Sheet 3 — Generation Methodology", SECTION_FONT, SECTION_FILL),
    ("Documents how the synthetic data was generated: templates, word lists, distribution, and rating logic.", None, None),
    ("Review whether the methodology is sound and note any concerns.", None, None),
    ("", None, None),
    ("Sheet 4 — Process Validation", SECTION_FONT, SECTION_FILL),
    ("Evaluate the generation process itself: template quality, word list coverage, distribution realism.", None, None),
    ("Score each aspect and provide written feedback.", None, None),
    ("", None, None),
    ("Sheet 5 — Summary & Verdict", SECTION_FONT, SECTION_FILL),
    ("After reviewing all 500 samples, provide per-category average scores and a final verdict.", None, None),
    ("Verdicts: Approve / Approve with Revisions / Major Revisions Needed / Reject", None, None),
    ("", None, None),
    ("Time Estimate", SECTION_FONT, SECTION_FILL),
    ("Approximately 2–3 hours for 500 reviews + process validation + summary.", None, None),
    ("", None, None),
    ("Contact", SECTION_FONT, SECTION_FILL),
    ("For questions: Fabiha Jalal", None, None),
]

for i, (text, font, fill) in enumerate(instructions, 1):
    cell = ws1.cell(row=i, column=1, value=text)
    if font:
        cell.font = font
    if fill:
        cell.fill = fill
    cell.alignment = Alignment(wrap_text=True)

ws1.column_dimensions["A"].width = 100

# ══════════════════════════════════════════════════════════════════════════════
# SHEET 2: All 500 Reviews
# ══════════════════════════════════════════════════════════════════════════════
ws2 = wb.create_sheet("Review Samples (500)")
ws2.sheet_properties.tabColor = "00B050"

headers = ["#", "Review Text", "Rating (Stars)", "Category", "Timestamp",
           "Realism (1-5)", "Category Correct? (Y/N)", "Comments"]
for col, h in enumerate(headers, 1):
    ws2.cell(row=1, column=col, value=h)
style_header_row(ws2, 1, len(headers))

# Sort reviews by category for easier batch reviewing
reviews_sorted = sorted(reviews, key=lambda r: (r["labels"][0], r["text"]))

for i, rev in enumerate(reviews_sorted, 1):
    row = i + 1
    ws2.cell(row=row, column=1, value=i).alignment = CENTER
    ws2.cell(row=row, column=1).border = THIN_BORDER

    ws2.cell(row=row, column=2, value=rev["text"]).alignment = WRAP
    ws2.cell(row=row, column=2).border = THIN_BORDER

    ws2.cell(row=row, column=3, value=rev["rating"]).alignment = CENTER
    ws2.cell(row=row, column=3).border = THIN_BORDER

    ws2.cell(row=row, column=4, value=rev["labels"][0]).alignment = CENTER
    ws2.cell(row=row, column=4).border = THIN_BORDER

    ws2.cell(row=row, column=5, value=rev["timestamp"]).alignment = CENTER
    ws2.cell(row=row, column=5).border = THIN_BORDER

    # Yellow cells for reviewer input
    for col in [6, 7, 8]:
        style_data_cell(ws2.cell(row=row, column=col), yellow=True)

    # Alternate row shading for readability
    if i % 2 == 0:
        for col in [1, 2, 3, 4, 5]:
            ws2.cell(row=row, column=col).fill = LIGHT_GRAY

# Add category separator rows
ws2.column_dimensions["A"].width = 5
ws2.column_dimensions["B"].width = 70
ws2.column_dimensions["C"].width = 12
ws2.column_dimensions["D"].width = 18
ws2.column_dimensions["E"].width = 22
ws2.column_dimensions["F"].width = 14
ws2.column_dimensions["G"].width = 20
ws2.column_dimensions["H"].width = 40

# Freeze header
ws2.freeze_panes = "A2"
# Auto-filter
ws2.auto_filter.ref = f"A1:H{len(reviews) + 1}"

# ══════════════════════════════════════════════════════════════════════════════
# SHEET 3: Generation Methodology
# ══════════════════════════════════════════════════════════════════════════════
ws3 = wb.create_sheet("Generation Methodology")
ws3.sheet_properties.tabColor = "FFC000"

methodology = [
    ("SYNTHETIC DATA GENERATION METHODOLOGY", "", ""),
    ("", "", ""),
    ("OVERVIEW", "", ""),
    ("Script Location", "ReviewAgent/scripts/download_datasets.py (lines 405–545)", ""),
    ("Method", "Template-based generation with random fill-in values", ""),
    ("Language", "Python 3.13 using random module", ""),
    ("Random Seed", "42 (fixed for reproducibility)", ""),
    ("Total Generated", "500 reviews", ""),
    ("", "", ""),
    ("WHY SYNTHETIC DATA IS NEEDED", "", ""),
    ("The MAALEJ dataset (5,008 human-annotated reviews) covers only 4 categories:", "", ""),
    ("  • Problem Discovery → mapped to bug_report", "", ""),
    ("  • Feature Request → mapped to feature_request", "", ""),
    ("  • User Experience → mapped to usability", "", ""),
    ("  • Rating → mapped to praise", "", ""),
    ("Missing categories with ZERO real training examples:", "", ""),
    ("  • performance (complaints about speed, battery, memory)", "", ""),
    ("  • compatibility (device/OS-specific issues)", "", ""),
    ("Without synthetic data, the classifier has no examples for these categories.", "", ""),
    ("", "", ""),
    ("GENERATION PROCESS (Step-by-Step)", "", ""),
    ("Step 1", "Randomly select a category using weighted probabilities (see distribution below)", ""),
    ("Step 2", "Pick a random sentence template for that category", ""),
    ("Step 3", "Fill placeholders ({action}, {device}, {feature}, etc.) with random values from word lists", ""),
    ("Step 4", "Assign a realistic star rating based on category sentiment", ""),
    ("Step 5", "Generate a random timestamp between Jan 1 – Sep 22, 2026", ""),
    ("Step 6", "Package as JSON with text, rating, app_id, timestamp, labels, source='synthetic'", ""),
    ("", "", ""),
    ("CATEGORY DISTRIBUTION", "", ""),
    ("Category", "Weight", "Actual Count (of 500)"),
    ("bug_report", "30%", "146 (29.2%)"),
    ("feature_request", "20%", "91 (18.2%)"),
    ("usability", "15%", "85 (17.0%)"),
    ("performance", "15%", "70 (14.0%)"),
    ("praise", "10%", "58 (11.6%)"),
    ("compatibility", "10%", "50 (10.0%)"),
    ("", "", ""),
    ("RATING ASSIGNMENT LOGIC", "", ""),
    ("Category", "Possible Ratings", "Distribution"),
    ("bug_report", "1, 1, 1, 2", "75% get 1-star, 25% get 2-star"),
    ("feature_request", "2, 3, 3", "33% get 2-star, 67% get 3-star"),
    ("performance", "1, 2, 2", "33% get 1-star, 67% get 2-star"),
    ("usability", "1, 2, 2, 3", "25% get 1-star, 50% get 2-star, 25% get 3-star"),
    ("compatibility", "1, 1, 2", "67% get 1-star, 33% get 2-star"),
    ("praise", "4, 5, 5, 5", "25% get 4-star, 75% get 5-star"),
    ("", "", ""),
    ("TEMPLATES BY CATEGORY", "", ""),
    ("", "", ""),
    ("Bug Reports (8 templates)", "", ""),
    ("1", 'App crashes when I {action}. This started after {version}.', ""),
    ("2", "Can't {action} anymore. It just {symptom} every time on my {device}.", ""),
    ("3", "{feature} is completely broken since the last update. {symptom}!", ""),
    ("4", "Getting a {symptom} whenever I try to {action} on {device} running {os}.", ""),
    ("5", "The app {symptom} every time I open {feature}. Please fix ASAP!", ""),
    ("6", "Since updating to {version}, the {feature} {symptom}. Terrible!", ""),
    ("7", "{feature} won't work on my {device}. It just {symptom}.", ""),
    ("8", "Keep getting {symptom} when using {feature}. Very frustrating.", ""),
    ("", "", ""),
    ("Feature Requests (6 templates)", "", ""),
    ("1", "I wish this app had {feature}. Would make it so much better!", ""),
    ("2", "Please add {feature}! Every other app has it.", ""),
    ("3", "It would be great if you could add {feature} to the app.", ""),
    ("4", "Can you please implement {feature}? I really need it.", ""),
    ("5", "The app needs {feature}. Without it, I'm switching to {competitor}.", ""),
    ("6", "Suggestion: add {feature}. It would improve the experience a lot.", ""),
    ("", "", ""),
    ("Performance Complaints (6 templates)", "", ""),
    ("1", "App is super slow on my {device}. Takes {time} to load.", ""),
    ("2", "The {feature} is extremely laggy. My {device} heats up like crazy.", ""),
    ("3", "Battery drain is insane with this app on {device} running {os}.", ""),
    ("4", "App uses too much memory. My {device} keeps killing it in background.", ""),
    ("5", "Loading time is {time} for {feature}. Way too slow on {device}.", ""),
    ("6", "The app makes my {device} overheat and drains battery in {time}.", ""),
    ("", "", ""),
    ("Usability Issues (6 templates)", "", ""),
    ("1", "The {feature} is so confusing. I can't figure out how to {action}.", ""),
    ("2", "UI is terrible. Can't find where to {action}. Too many menus!", ""),
    ("3", "The new design is awful. I can't {action} anymore. Make it simpler!", ""),
    ("4", "Text is too small on {feature}. Can't read anything on my {device}.", ""),
    ("5", "Buttons are too close together on {feature}. Keep tapping the wrong one.", ""),
    ("6", "Navigation is very confusing. Took me {time} to find {feature}.", ""),
    ("", "", ""),
    ("Compatibility Issues (4 templates)", "", ""),
    ("1", "App doesn't work on my {device} with {os}. Just shows a blank screen.", ""),
    ("2", "Crashes immediately on {device} running {os}. Works fine on other devices.", ""),
    ("3", "Not compatible with {os} on {device}. Please update for newer devices!", ""),
    ("4", "The {feature} looks broken on my {device} with {os}. Layout is messed up.", ""),
    ("", "", ""),
    ("Praise (5 templates)", "", ""),
    ("1", "Love this app! The {feature} is amazing. 5 stars!", ""),
    ("2", "Best app ever! The {feature} works perfectly on my {device}.", ""),
    ("3", "Great update! The new {feature} is exactly what I needed.", ""),
    ("4", "Keep up the great work! {feature} is so smooth and fast.", ""),
    ("5", "Finally an app that does {feature} right. Highly recommended!", ""),
    ("", "", ""),
    ("FILL-IN VALUE LISTS (WORD BANKS)", "", ""),
    ("", "", ""),
    ("Placeholder", "Values", "Count"),
    ("{action}", "login, sign up, checkout, upload a photo, send a message, search, update my profile, sync my data, make a payment, open settings, share a post, download content", "12"),
    ("{symptom}", "crashes, freezes, shows an error, force closes, goes to a blank screen, hangs for minutes, restarts, loses my data, shows a white screen", "9"),
    ("{feature} (bug/perf/usability/compat)", "login, camera, dark mode, notifications, payment, search, profile page, settings, home screen, chat, photo editor, file manager, calendar, maps, voice input", "15"),
    ("{feature} (feature_request)", "dark mode, widget support, offline mode, biometric login, custom themes, export to PDF, multi-language support, cloud backup, split screen, desktop sync", "10"),
    ("{device}", "iPhone 15 Pro, iPhone 14, Samsung Galaxy S24, Google Pixel 8, OnePlus 12, Samsung Galaxy A54, iPad Pro, Xiaomi 14", "8"),
    ("{os}", "iOS 18.2, iOS 17.5, Android 15, Android 14, Android 13", "5"),
    ("{version}", "v3.2, v3.2.1, v3.1, v3.0, v2.9", "5"),
    ("{time}", "10 seconds, 30 seconds, a minute, 2 minutes, forever", "5"),
    ("{competitor}", "the competitor, another app, AppX, the other app", "4"),
    ("", "", ""),
    ("THEORETICAL COMBINATION SPACE", "", ""),
    ("For bug_report alone: 8 × 12 × 9 × 15 × 8 × 5 × 5 = 43,200,000 unique reviews possible", "", ""),
    ("Only 500 samples are generated, using a tiny fraction of the combinatorial space.", "", ""),
    ("", "", ""),
    ("DATA SOURCE REFERENCES", "", ""),
    ("MAALEJ Dataset", "Maalej et al. (2016) 'On the Automatic Classification of App Reviews' — 5,008 human-annotated reviews from 4 categories", "github.com/mohammadzaeem/classification_of_app_reviews"),
    ("RRGen Dataset", "Gao et al. (2019) 'Automating App Review Response Generation' — 310,031 review-response pairs (unlabeled)", "Downloaded via gdown"),
    ("GUZMAN Dataset", "Guzman & Maalej (2014) + Dabrowski IS-22 — 2,062 aspect-sentiment annotations", "github.com/2022-IS/"),
    ("Synthetic (this data)", "Template-based, generated by download_datasets.py with seed=42", "This validation form"),
    ("", "", ""),
    ("KNOWN LIMITATIONS", "", ""),
    ("1. Templates produce more predictable language than real reviews (fewer typos, slang, emoji)", "", ""),
    ("2. Word lists may not cover all real-world devices, OS versions, or app features", "", ""),
    ("3. Ratings are deterministic per category (real reviews have more variance)", "", ""),
    ("4. No multi-label synthetic reviews (real reviews can belong to multiple categories)", "", ""),
    ("5. No non-English reviews (real app stores have multilingual content)", "", ""),
]

for i, (a, b, c) in enumerate(methodology, 1):
    ws3.cell(row=i, column=1, value=a).alignment = WRAP
    ws3.cell(row=i, column=2, value=b).alignment = WRAP
    ws3.cell(row=i, column=3, value=c).alignment = WRAP
    # Style section headers
    if a in ["OVERVIEW", "WHY SYNTHETIC DATA IS NEEDED", "GENERATION PROCESS (Step-by-Step)",
             "CATEGORY DISTRIBUTION", "RATING ASSIGNMENT LOGIC", "TEMPLATES BY CATEGORY",
             "FILL-IN VALUE LISTS (WORD BANKS)", "THEORETICAL COMBINATION SPACE",
             "DATA SOURCE REFERENCES", "KNOWN LIMITATIONS"]:
        for col in range(1, 4):
            ws3.cell(row=i, column=col).font = SECTION_FONT
            ws3.cell(row=i, column=col).fill = SECTION_FILL
    if a == "SYNTHETIC DATA GENERATION METHODOLOGY":
        ws3.cell(row=i, column=1).font = Font(name="Calibri", bold=True, size=14, color="2F5496")

ws3.column_dimensions["A"].width = 45
ws3.column_dimensions["B"].width = 90
ws3.column_dimensions["C"].width = 50

# ══════════════════════════════════════════════════════════════════════════════
# SHEET 4: Process Validation
# ══════════════════════════════════════════════════════════════════════════════
ws4 = wb.create_sheet("Process Validation")
ws4.sheet_properties.tabColor = "FF0000"

process_headers = ["Aspect", "Question", "Score (1-5)", "Comments"]
for col, h in enumerate(process_headers, 1):
    ws4.cell(row=1, column=col, value=h)
style_header_row(ws4, 1, 4)

process_items = [
    ("Template Quality", "Do the templates capture realistic app review patterns and language?"),
    ("Template Diversity", "Are there enough templates per category to avoid repetitiveness?"),
    ("Word List Coverage", "Are the device names, OS versions, and features current and comprehensive?"),
    ("Word List Realism", "Do the fill-in values produce natural-sounding reviews when combined?"),
    ("Category Distribution", "Is the weighted distribution (30% bugs, 20% features, etc.) realistic?"),
    ("Rating Assignment", "Are the star rating distributions per category realistic?"),
    ("Language Naturalness", "Do generated reviews sound like real user-written text (informal, varied)?"),
    ("Missing Patterns", "Are there common review patterns NOT captured by the templates?"),
    ("Edge Cases", "Does the generation handle edge cases (short reviews, emotional language, typos)?"),
    ("Overall Methodology", "Is the template-based generation approach appropriate for this use case?"),
]

for i, (aspect, question) in enumerate(process_items, 2):
    ws4.cell(row=i, column=1, value=aspect).alignment = WRAP
    ws4.cell(row=i, column=1).border = THIN_BORDER
    ws4.cell(row=i, column=2, value=question).alignment = WRAP
    ws4.cell(row=i, column=2).border = THIN_BORDER
    style_data_cell(ws4.cell(row=i, column=3), yellow=True)
    style_data_cell(ws4.cell(row=i, column=4), yellow=True)

ws4.column_dimensions["A"].width = 25
ws4.column_dimensions["B"].width = 70
ws4.column_dimensions["C"].width = 14
ws4.column_dimensions["D"].width = 50

# Add open-ended questions
row = len(process_items) + 3
ws4.cell(row=row, column=1, value="OPEN-ENDED FEEDBACK").font = SECTION_FONT
ws4.cell(row=row, column=1).fill = SECTION_FILL
for col in range(2, 5):
    ws4.cell(row=row, column=col).fill = SECTION_FILL

open_questions = [
    "What templates or patterns are missing that real reviews commonly use?",
    "What devices, OS versions, or features should be added to the word lists?",
    "How could the generation be improved to produce more realistic reviews?",
    "Any other concerns about using this synthetic data for classifier training?",
]
for i, q in enumerate(open_questions, row + 1):
    ws4.cell(row=i, column=1, value=q).alignment = WRAP
    ws4.cell(row=i, column=1).border = THIN_BORDER
    ws4.merge_cells(start_row=i, start_column=2, end_row=i, end_column=4)
    style_data_cell(ws4.cell(row=i, column=2), yellow=True)
    ws4.row_dimensions[i].height = 60

# ══════════════════════════════════════════════════════════════════════════════
# SHEET 5: Summary & Verdict
# ══════════════════════════════════════════════════════════════════════════════
ws5 = wb.create_sheet("Summary & Verdict")
ws5.sheet_properties.tabColor = "7030A0"

ws5.cell(row=1, column=1, value="VALIDATION SUMMARY").font = Font(name="Calibri", bold=True, size=14, color="2F5496")

# Per-category summary
ws5.cell(row=3, column=1, value="PER-CATEGORY SCORES").font = SECTION_FONT
ws5.cell(row=3, column=1).fill = SECTION_FILL
for col in range(2, 7):
    ws5.cell(row=3, column=col).fill = SECTION_FILL

cat_headers = ["Category", "Sample Count", "Avg Realism (1-5)", "% Category Correct", "Key Issues"]
for col, h in enumerate(cat_headers, 1):
    ws5.cell(row=4, column=col, value=h)
style_header_row(ws5, 4, 5)

categories = [
    ("bug_report", 146),
    ("feature_request", 91),
    ("usability", 85),
    ("performance", 70),
    ("praise", 58),
    ("compatibility", 50),
    ("OVERALL", 500),
]
for i, (cat, count) in enumerate(categories, 5):
    ws5.cell(row=i, column=1, value=cat).border = THIN_BORDER
    ws5.cell(row=i, column=2, value=count).alignment = CENTER
    ws5.cell(row=i, column=2).border = THIN_BORDER
    style_data_cell(ws5.cell(row=i, column=3), yellow=True)
    style_data_cell(ws5.cell(row=i, column=4), yellow=True)
    style_data_cell(ws5.cell(row=i, column=5), yellow=True)
    if cat == "OVERALL":
        ws5.cell(row=i, column=1).font = Font(bold=True)

# Verdict section
verdict_row = 14
ws5.cell(row=verdict_row, column=1, value="FINAL VERDICT").font = SECTION_FONT
ws5.cell(row=verdict_row, column=1).fill = SECTION_FILL
for col in range(2, 6):
    ws5.cell(row=verdict_row, column=col).fill = SECTION_FILL

verdicts = [
    ("Verdict (select one):", "Approve / Approve with Revisions / Major Revisions Needed / Reject"),
    ("Justification:", ""),
    ("Critical issues that MUST be fixed:", ""),
    ("Suggestions for improvement:", ""),
    ("Approved for training use?", "Yes / No"),
]
for i, (label, hint) in enumerate(verdicts, verdict_row + 1):
    ws5.cell(row=i, column=1, value=label).font = Font(bold=True)
    ws5.cell(row=i, column=1).border = THIN_BORDER
    ws5.merge_cells(start_row=i, start_column=2, end_row=i, end_column=5)
    cell = ws5.cell(row=i, column=2)
    cell.value = hint if hint else None
    style_data_cell(cell, yellow=True)
    ws5.row_dimensions[i].height = 40 if not hint else 25

# Reviewer info
info_row = verdict_row + len(verdicts) + 2
ws5.cell(row=info_row, column=1, value="REVIEWER INFORMATION").font = SECTION_FONT
ws5.cell(row=info_row, column=1).fill = SECTION_FILL
for col in range(2, 6):
    ws5.cell(row=info_row, column=col).fill = SECTION_FILL

info_fields = ["Reviewer Name:", "Date:", "Affiliation:", "Expertise Area:"]
for i, field in enumerate(info_fields, info_row + 1):
    ws5.cell(row=i, column=1, value=field).font = Font(bold=True)
    ws5.cell(row=i, column=1).border = THIN_BORDER
    ws5.merge_cells(start_row=i, start_column=2, end_row=i, end_column=5)
    style_data_cell(ws5.cell(row=i, column=2), yellow=True)

ws5.column_dimensions["A"].width = 30
ws5.column_dimensions["B"].width = 18
ws5.column_dimensions["C"].width = 20
ws5.column_dimensions["D"].width = 22
ws5.column_dimensions["E"].width = 40

# ── Save ─────────────────────────────────────────────────────────────────────
output_path = "/Users/fabihajalal/Desktop/Review Agent/Synthetic_Data_Validation_Form_500.xlsx"
wb.save(output_path)
print(f"Saved: {output_path}")
print(f"Reviews included: {len(reviews)}")
print("Sheets: Instructions | Review Samples (500) | Generation Methodology | Process Validation | Summary & Verdict")
