"""
Stage-4 re-run: LLM with IssueSpec versus the same LLM without it.

Why this replaces the earlier Stage-4 result
--------------------------------------------
The four conditions behind the previously reported +2.35 Likert gain were produced by
deterministic template composers, not by a language model (scripts/generate_reviewagent_*.py
contain no model calls). The two arms therefore differed in authorial register as well as in
whether the IssueSpec was supplied: one read as broken lemmatised English at 78 words, the
other as polished prose at 123 words. That gap measured the composer as much as the
specification.

This run removes the confound. Both arms are generated by the same model with the same
retrieved context, and differ only in whether the validated IssueSpec was in the prompt.
Mean lengths are 105 and 97 words, so a rater cannot separate the conditions on surface
features.

The script also runs the independence check that the earlier round failed: if two raters'
scores are a third rater's vector with small perturbations, their deviations from that rater
will not overlap and will share a magnitude. Real independent rating produces overlap close
to chance and a spread of magnitudes.

Outputs
    data/processed/inter_annotator/stage4_llm_rerun.json
    data/processed/inter_annotator/stage4_llm_rerun.txt

Usage
    python3 scripts/run_stage4_llm_rerun.py
"""

import json
import statistics
from collections import Counter
from itertools import combinations
from pathlib import Path

import numpy as np
from numbers_parser import Document
from scipy import stats

REPO = Path(__file__).resolve().parent.parent
HANDOFF = REPO / "paper/experiments/labmate_handoff"
KEY = REPO / "annotator_materials/stage4_llm_rerun/blinding_key.json"
OUT = REPO / "data/processed/inter_annotator/stage4_llm_rerun.json"
OUT_TXT = OUT.with_suffix(".txt")
RATERS = ["A", "D", "E"]
BOOT = 10_000
SEED = 42


def load(code):
    path = HANDOFF / f"stage4_llm_rerun_{code}.numbers"
    for sheet in Document(str(path)).sheets:
        for table in sheet.tables:
            rows = table.rows(values_only=True)
            hdr = [str(c) for c in rows[0]]
            if "quality_1_to_5" not in hdr:
                continue
            ri, bi = hdr.index("review_index"), hdr.index("blind_id")
            qi, si = hdr.index("quality_1_to_5"), hdr.index("specificity_1_to_5")
            hi = hdr.index("helpful_y_n")
            out = {}
            for r in rows[1:]:
                if r[ri] is None or r[qi] in (None, ""):
                    continue
                out[(int(float(r[ri])), str(r[bi]).strip())] = {
                    "quality": float(r[qi]),
                    "specificity": float(r[si]) if r[si] not in (None, "") else None,
                    "helpful": str(r[hi]).strip().upper() if r[hi] else "",
                }
            return out
    raise SystemExit(f"no ratings table in {path}")


def cohen_kappa(x, y):
    n = len(x)
    po = sum(1 for a, b in zip(x, y) if a == b) / n
    cx, cy = Counter(x), Counter(y)
    pe = sum(cx[c] / n * cy[c] / n for c in set(cx) | set(cy))
    return po, ((po - pe) / (1 - pe) if pe < 1 else float("nan"))


def weighted_kappa(x, y, cats=(1.0, 2.0, 3.0, 4.0, 5.0)):
    k = len(cats)
    idx = {c: i for i, c in enumerate(cats)}
    n = len(x)
    obs = np.zeros((k, k))
    for a, b in zip(x, y):
        obs[idx[a]][idx[b]] += 1
    obs /= n
    exp = np.outer(obs.sum(axis=1), obs.sum(axis=0))
    w = np.array([[((i - j) / (k - 1)) ** 2 for j in range(k)] for i in range(k)])
    denom = (w * exp).sum()
    return 1 - (w * obs).sum() / denom if denom else float("nan")


def cliffs_delta(a, b):
    a, b = np.asarray(a), np.asarray(b)
    gt = sum((x > b).sum() for x in a)
    lt = sum((x < b).sum() for x in a)
    return (gt - lt) / (len(a) * len(b))


def main():
    key = json.loads(KEY.read_text())
    raters = {c: load(c) for c in RATERS}
    for c, v in raters.items():
        print(f"  rater {c}: {len(v)} rows scored")

    common = sorted(set.intersection(*(set(v) for v in raters.values())))
    print(f"  rows scored by all three: {len(common)}")

    report = {"n_rows": len(common), "raters": RATERS,
              "design": "same LLM, same retrieved context, IssueSpec present or absent"}

    # ---- independence check ------------------------------------------------
    q = {c: [raters[c][k]["quality"] for k in common] for c in RATERS}
    indep = {}
    for a, b in combinations(RATERS, 2):
        dev = [i for i in range(len(common)) if q[a][i] != q[b][i]]
        indep[f"{a}_vs_{b}"] = {
            "rows_differing": len(dev),
            "pct_differing": round(100 * len(dev) / len(common), 1),
            "max_abs_diff": max((abs(q[a][i] - q[b][i]) for i in dev), default=0),
        }
    dA = {i for i in range(len(common)) if q["D"][i] != q["A"][i]}
    eA = {i for i in range(len(common)) if q["E"][i] != q["A"][i]}
    expected = len(dA) * len(eA) / len(common)
    report["independence"] = {
        "pairwise": indep,
        "D_deviations_from_A": len(dA), "E_deviations_from_A": len(eA),
        "overlap_observed": len(dA & eA), "overlap_expected_if_independent": round(expected, 1),
        "D_magnitudes": {str(k): v for k, v in
                         sorted(Counter(abs(q["D"][i] - q["A"][i]) for i in dA).items())},
        "E_magnitudes": {str(k): v for k, v in
                         sorted(Counter(abs(q["E"][i] - q["A"][i]) for i in eA).items())},
    }

    # ---- unblind and compute the gain --------------------------------------
    cond = {k: key[f"{k[0]}:{k[1]}"] for k in common}
    reviews = sorted({k[0] for k in common})
    rng = np.random.default_rng(SEED)
    report["per_rater"] = {}
    for c in RATERS:
        by_cond = {}
        for k in common:
            by_cond.setdefault(cond[k], []).append(raters[c][k])
        means = {cc: {"quality": round(statistics.mean(x["quality"] for x in v), 3),
                      "specificity": round(statistics.mean(
                          x["specificity"] for x in v if x["specificity"] is not None), 3),
                      "helpful_pct": round(100 * sum(1 for x in v if x["helpful"] == "Y") / len(v), 1)}
                 for cc, v in by_cond.items()}
        paired_full, paired_no = [], []
        for r in reviews:
            f = [raters[c][k]["quality"] for k in common
                 if k[0] == r and cond[k] == "reviewagent_full_LLM"]
            n = [raters[c][k]["quality"] for k in common
                 if k[0] == r and cond[k] == "reviewagent_no_spec_LLM"]
            if f and n:
                paired_full.append(f[0])
                paired_no.append(n[0])
        diff = np.array(paired_full) - np.array(paired_no)
        boot = np.array([rng.choice(diff, size=len(diff), replace=True).mean()
                         for _ in range(BOOT)])
        try:
            p = stats.wilcoxon(paired_full, paired_no).pvalue
        except ValueError:
            p = float("nan")
        sd = diff.std(ddof=1)
        report["per_rater"][c] = {
            "condition_means": means, "n_pairs": len(diff),
            "mean_gain": round(float(diff.mean()), 3),
            "ci95": [round(float(x), 3) for x in np.percentile(boot, [2.5, 97.5])],
            "wilcoxon_p": float(p),
            "cohens_dz": round(float(diff.mean() / sd), 3) if sd else float("nan"),
            "cliffs_delta": round(float(cliffs_delta(paired_full, paired_no)), 3),
            "wins": int((diff > 0).sum()), "losses": int((diff < 0).sum()),
            "ties": int((diff == 0).sum()),
        }

    pooled_full, pooled_no = [], []
    for r in reviews:
        f = [statistics.mean(raters[c][k]["quality"] for c in RATERS)
             for k in common if k[0] == r and cond[k] == "reviewagent_full_LLM"]
        n = [statistics.mean(raters[c][k]["quality"] for c in RATERS)
             for k in common if k[0] == r and cond[k] == "reviewagent_no_spec_LLM"]
        if f and n:
            pooled_full.append(f[0])
            pooled_no.append(n[0])
    diff = np.array(pooled_full) - np.array(pooled_no)
    boot = np.array([rng.choice(diff, size=len(diff), replace=True).mean() for _ in range(BOOT)])
    report["pooled"] = {
        "n_pairs": len(diff), "mean_gain": round(float(diff.mean()), 3),
        "ci95": [round(float(x), 3) for x in np.percentile(boot, [2.5, 97.5])],
        "wilcoxon_p": float(stats.wilcoxon(pooled_full, pooled_no).pvalue),
        "cohens_dz": round(float(diff.mean() / diff.std(ddof=1)), 3),
        "cliffs_delta": round(float(cliffs_delta(pooled_full, pooled_no)), 3),
        "wins": int((diff > 0).sum()), "losses": int((diff < 0).sum()),
        "ties": int((diff == 0).sum()),
        "mean_full": round(float(np.mean(pooled_full)), 3),
        "mean_no_spec": round(float(np.mean(pooled_no)), 3),
    }

    # ---- reliability --------------------------------------------------------
    rel = {}
    for a, b in combinations(RATERS, 2):
        x, y = q[a], q[b]
        po_h, k_h = cohen_kappa([raters[a][k]["helpful"] for k in common],
                                [raters[b][k]["helpful"] for k in common])
        rel[f"{a}_vs_{b}"] = {
            "quality_exact_pct": round(100 * sum(1 for i, j in zip(x, y) if i == j) / len(x), 1),
            "quality_within1_pct": round(100 * sum(1 for i, j in zip(x, y) if abs(i - j) <= 1) / len(x), 1),
            "quality_weighted_kappa": round(float(weighted_kappa(x, y)), 3),
            "quality_pearson": round(float(np.corrcoef(x, y)[0, 1]), 3),
            "helpful_exact_pct": round(100 * po_h, 1),
            "helpful_cohen_kappa": round(float(k_h), 3),
        }
    report["reliability"] = rel

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(report, indent=2))

    L = ["=" * 76, "STAGE-4 RE-RUN: LLM WITH IssueSpec VERSUS THE SAME LLM WITHOUT IT", "=" * 76, "",
         f"{report['n_rows']} blinded rows, {len(reviews)} reviews x 2 conditions, three raters",
         "Both arms: same model, same retrieved context; the only difference is the IssueSpec.", "",
         "-" * 76, "INDEPENDENCE CHECK", "-" * 76]
    for pair, v in indep.items():
        L.append(f"  {pair}: {v['rows_differing']}/{report['n_rows']} rows differ "
                 f"({v['pct_differing']}%), largest disagreement {v['max_abs_diff']:.0f} points")
    ind = report["independence"]
    L += [f"  D and E deviate from A on {ind['D_deviations_from_A']} and "
          f"{ind['E_deviations_from_A']} rows; they overlap on {ind['overlap_observed']}, "
          f"chance would give about {ind['overlap_expected_if_independent']}",
          f"  deviation magnitudes, D: {ind['D_magnitudes']}   E: {ind['E_magnitudes']}",
          "  Overlap near chance and a spread of magnitudes is what independent rating looks like.",
          "", "-" * 76, "RESULT", "-" * 76,
          f"  {'rater':8s}{'no_spec':>10s}{'full':>9s}{'gain':>8s}{'CI95':>18s}{'p':>11s}{'W/L/T':>12s}"]
    for c in RATERS:
        v = report["per_rater"][c]
        m = v["condition_means"]
        L.append(f"  {c:8s}{m['reviewagent_no_spec_LLM']['quality']:>10.2f}"
                 f"{m['reviewagent_full_LLM']['quality']:>9.2f}{v['mean_gain']:>8.2f}"
                 f"{'[' + f'{v[chr(99)+chr(105)+chr(57)+chr(53)][0]:+.2f}, {v[chr(99)+chr(105)+chr(57)+chr(53)][1]:+.2f}' + ']':>18s}"
                 f"{v['wilcoxon_p']:>11.2e}{f'{v[chr(119)+chr(105)+chr(110)+chr(115)]}/{v[chr(108)+chr(111)+chr(115)+chr(115)+chr(101)+chr(115)]}/{v[chr(116)+chr(105)+chr(101)+chr(115)]}':>12s}")
    p = report["pooled"]
    L.append(f"  {'pooled':8s}{p['mean_no_spec']:>10.2f}{p['mean_full']:>9.2f}{p['mean_gain']:>8.2f}"
             f"{'[' + f'{p[chr(99)+chr(105)+chr(57)+chr(53)][0]:+.2f}, {p[chr(99)+chr(105)+chr(57)+chr(53)][1]:+.2f}' + ']':>18s}"
             f"{p['wilcoxon_p']:>11.2e}{f'{p[chr(119)+chr(105)+chr(110)+chr(115)]}/{p[chr(108)+chr(111)+chr(115)+chr(115)+chr(101)+chr(115)]}/{p[chr(116)+chr(105)+chr(101)+chr(115)]}':>12s}")
    L += [f"  pooled Cliff's delta {p['cliffs_delta']}, Cohen's dz {p['cohens_dz']}", "",
          "-" * 76, "RELIABILITY", "-" * 76]
    for pair, v in rel.items():
        L.append(f"  {pair}: quality exact {v['quality_exact_pct']}%, within-1 "
                 f"{v['quality_within1_pct']}%, weighted kappa {v['quality_weighted_kappa']}, "
                 f"r {v['quality_pearson']}; helpful kappa {v['helpful_cohen_kappa']}")
    L.append("")
    OUT_TXT.write_text("\n".join(L) + "\n")
    print("\n" + "\n".join(L))


if __name__ == "__main__":
    main()
